//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SOboe.rc
//
#define IDR_MANIFEST                    1
#define IDB_ICONIMG                     100
#define IDB_TREEIMAGE                   101
#define IDB_TOOLBAR                     102
#define IDR_DLGMENU                     110
#define IDR_FOR_ICON                    111
#define IDR_FOR_NORMAL                  112
#define IDR_FOR_TITLE                   113
#define IDR_MAINFRAME                   114
#define IDR_OLEDROP                     115
#define IDR_SOBOETYPE                   116
#define IDR_EDITWINDOW                  117
#define IDI_ABSENCE                     120
#define IDI_HIDE                        121
#define IDI_RECEIVE                     122
#define IDD_ABOUTBOX                    150
#define IDD_ABOUTBOX98                  151
#define IDD_ABOUTBOXNT                  152
#define IDD_BASEPAGE                    153
#define IDD_DATASEL                     154
#define IDD_DELLIST                     155
#define IDD_EXTENDPAGE                  156
#define IDD_EXTSETTINGDLG               157
#define IDD_PWCHECK                     158
#define IDD_RESULTCHECK                 159
#define IDD_SENDERINFO                  160
#define IDD_SENDPAGE                    161
#define IDD_SENDWORKER                  162
#define IDD_TIMERPAGE                   163
#define IDC_ADDNODE                     200
#define IDC_AFTERNOTIFY                 201
#define IDC_APPENDHEAD                  202
#define IDC_APPENDSIGNATURE             203
#define IDC_APPENDTAIL                  204
#define IDC_APPENDTIME                  205
#define IDC_BEFORENOTIFY                206
#define IDC_BEFORSPIN                   207
#define IDC_CALCRESIZE                  208
#define IDC_CENTER                      209
#define IDC_COLOR                       210
#define IDC_COPYRESTORE                 211
#define IDC_DATALIST                    212
#define IDC_DAY                         213
#define IDC_DELCOMP                     214
#define IDC_DELETE                      215
#define IDC_DELLIST                     216
#define IDC_DELNODE                     217
#define IDC_DELONQUIT                   218
#define IDC_DXLEDITHELPER               219
#define IDC_DXLSEL                      220
#define IDC_EDTRESULT1                  221
#define IDC_EDTRESULT2                  222
#define IDC_ENTRYINFO                   223
#define IDC_ENTRYNAME                   224
#define IDC_EXPORT                      225
#define IDC_EXTSETTING                  226
#define IDC_FILE                        227
#define IDC_FILESEL                     228
#define IDC_FILTER                      229
#define IDC_FONT                        230
#define IDC_GDI                         231
#define IDC_GDIPER                      232
#define IDC_GOSUPORT                    233
#define IDC_HEAD                        234
#define IDC_HOUR                        235
#define IDC_ICONFILTER                  236
#define IDC_ICONLIST                    237
#define IDC_ITEMDOWN                    238
#define IDC_ITEMUP                      239
#define IDC_LINK                        240
#define IDC_LISTUPTOTAIL                241
#define IDC_MEMOEDIT                    242
#define IDC_MIN                         243
#define IDC_MONTH                       244
#define IDC_NODEEDIT                    245
#define IDC_NODELIST                    246
#define IDC_NODELISTUPDATE              247
#define IDC_NODETREE                    248
#define IDC_NOTIFYOPEN                  249
#define IDC_NOTIFYRESULT                250
#define IDC_NOTIFYSHIFT                 251
#define IDC_OPENPASSWORD                252
#define IDC_OTHERRESULT                 253
#define IDC_PACKSEND                    254
#define IDC_PAGEFILE                    255
#define IDC_PAGEFILEPER                 256
#define IDC_PARAMETERS                  257
#define IDC_PARAMETERSSEL               258
#define IDC_PASSWORD1ST                 259
#define IDC_PASSWORD2ND                 260
#define IDC_PASSWORDENABLE              261
#define IDC_PHYSICAL                    262
#define IDC_PHYSICALPER                 263
#define IDC_PREVIEW                     264
#define IDC_PROTCOL                     265
#define IDC_PWINPUT                     266
#define IDC_RECEIVETIME                 267
#define IDC_RELOAD                      268
#define IDC_RESTORE                     269
#define IDC_RESULT1                     270
#define IDC_RESULT2                     271
#define IDC_RESULT3                     272
#define IDC_RESULT3EDIT                 273
#define IDC_REVERSE                     274
#define IDC_SAVETEXT                    275
#define IDC_SENDCENTER                  276
#define IDC_SENDLIST                    277
#define IDC_SENDMASTER                  278
#define IDC_SENDNODE                    279
#define IDC_SENDRESIZE                  280
#define IDC_SENDTIME                    281
#define IDC_SPNDAY                      282
#define IDC_SPNHOUR                     283
#define IDC_SPNMIN                      284
#define IDC_SPNMONTH                    285
#define IDC_SYSTEM                      286
#define IDC_SYSTEMPER                   287
#define IDC_TAILE                       288
#define IDC_TIMERENABLE                 289
#define IDC_TIMEREXEC                   290
#define IDC_TIMERTYPE                   291
#define IDC_TITLE                       292
#define IDC_USEDNXL                     293
#define IDC_USER                        294
#define IDC_USERPER                     295
#define IDC_WAVEFILE                    296
#define IDC_WAVEPLAY                    297
#define IDC_WAVSEL                      298
#define IDC_WEEKLIST                    299
#define IDC_ZODER                       300
#define IDC_SENDRESULTLIST              301
#define IDC_FONTCOLOR                   302
#define IDC_TEMPLET                     303
#define IDC_EXEDITTOOLBAR               304
#define IDC_TITLETITLE                  305
#define IDC_AUTOCLOSE                   306
#define IDC_PRINTPRGRS                  307
#define IDC_SLDALPHABLEND               308
#define IDC_DELETEAFTERSEND             309
#define IDC_ICONSEL                     310
#define IDC_SCROLLBAR1                  312
#define IDM_ABSENCE                     400
#define IDM_ALL_ICON                    401
#define IDM_ALL_NORMAL                  402
#define IDM_ALL_ONCEHIDE                403
#define IDM_ALL_TITLE                   404
#define IDM_ALL_TOP                     405
#define IDM_ALLICON                     406
#define IDM_ALLNORMAL                   407
#define IDM_ALLONCEHIDE                 408
#define IDM_ALLTOP                      409
#define IDM_APP_ABOUT                   410
#define IDM_APPENDPASTE                 411
#define IDM_ARRANGE_ICON                412
#define IDM_ARRANGE_NORMAL              413
#define IDM_ARRANGECHIP                 414
#define IDM_ARRANGEICON                 415
#define IDM_CHIPEXPORT                  416
#define IDM_CHIPINPORT                  417
#define IDM_CHIPSAVE                    418
#define IDM_CHIPSEND                    419
#define IDM_CLIENTRESERCH               420
#define IDM_COPY                        421
#define IDM_COPY_MEMODATA               422
#define IDM_COPYRESTORE                 423
#define IDM_CREATEPASTE                 424
#define IDM_CUSTOM                      425
#define IDM_DATALIST                    426
#define IDM_DD_CREATEPASTE              427
#define IDM_DD_LINKPASTE                428
#define IDM_DD_OVERPASTE                429
#define IDM_DD_PASTE                    430
#define IDM_DELETE                      431
#define IDM_DELLIST                     432
#define IDM_DELONQUIT                   433
#define IDM_EXIT                        434
#define IDM_HELP                        435
#define IDM_HIDE                        436
#define IDM_LINKEXEC                    437
#define IDM_LINKPASTE                   438
#define IDM_MEMOEXPORT                  439
#define IDM_MEMOIMPORT                  440
#define IDM_NEWMEMO                     441
#define IDM_NOHOME                      442
#define IDM_NONPOPUP                    443
#define IDM_OVERPASTE                   444
#define IDM_PASTE                       445
#define IDM_PASTE_APPEND                446
#define IDM_PASTE_CREATE                447
#define IDM_PASTE_LINK                  448
#define IDM_PASTE_OVERWRITE             449
#define IDM_POSLOCK                     450
#define IDM_REEDIT                      451
#define IDM_REPLY                       452
#define IDM_SEETHROUGH                  453
#define IDM_SEETROUGH                   454
#define IDM_SEND                        455
#define IDM_SEND_DIRECT                 456
#define IDM_SENDCHIP                    457
#define IDM_SENDER                      458
#define IDM_SHELLPASTE                  459
#define IDM_TEMPLET0MENU                460
#define IDM_TEMPLET1MENU                461
#define IDM_TEMPLET2MENU                462
#define IDM_TEMPLET3MENU                463
#define IDM_TEMPLET4MENU                464
#define IDM_TEMPLET5MENU                465
#define IDM_TEMPLET6MENU                466
#define IDM_TEMPLET7MENU                467
#define IDM_TEMPLET8MENU                468
#define IDM_TEMPLET9MENU                469
#define IDM_TEXTSAVE                    470
#define IDM_TOICON                      471
#define IDM_TONORMAL                    472
#define IDM_TOTITLE                     473
#define IDM_UNDO                        474
#define IDM_SAVENOW                     475
#define IDM_STOPNXL                     476
#define IDM_STARTNXL                    477
#define IDM_TEMPLET0MENU_S              478
#define IDM_TEMPLET1MENU_S              479
#define IDM_TEMPLET2MENU_S              480
#define IDM_TEMPLET3MENU_S              481
#define IDM_TEMPLET4MENU_S              482
#define IDM_TEMPLET5MENU_S              483
#define IDM_TEMPLET6MENU_S              484
#define IDM_TEMPLET7MENU_S              485
#define IDM_TEMPLET8MENU_S              486
#define IDM_TEMPLET9MENU_S              487
#define IDM_NORMAL_ZORDER               489
#define IDM_TOP_ZORDER                  490
#define IDM_BOTTOM_ZORDER               491
#define IDM_FONTSEL                     493
#define IDM_FORECOLOR                   494
#define IDM_BACKCOLOR                   495
#define IDM_CALCRESIZE                  497
#define IDM_TEMPLET                     498
#define IDM_LINK                        499
#define IDM_TIMER                       500
#define IDM_ZORDER                      501
#define IDM_DXLSEL                      502
#define IDM_DXLEDITHELPER               503
#define IDM_PWSET                       504
#define IDM_DXLITEMXX                   505
#define IDM_DXLITEM00                   506
#define IDM_DXLITEM01                   507
#define IDM_DXLITEM02                   508
#define IDM_DXLITEM03                   509
#define IDM_DXLITEM04                   510
#define IDM_DXLITEM05                   511
#define IDM_DXLITEM06                   512
#define IDM_DXLITEM07                   513
#define IDM_DXLITEM08                   514
#define IDM_DXLITEM09                   515
#define IDM_DXLITEM10                   516
#define IDM_DXLITEM11                   517
#define IDM_DXLITEM12                   518
#define IDM_DXLITEM13                   519
#define IDM_DXLITEM14                   520
#define IDM_DXLITEM15                   521
#define IDM_DXLITEM16                   522
#define IDM_DXLITEM17                   523
#define IDM_DXLITEM18                   524
#define IDM_DXLITEM19                   525
#define IDM_DXLITEM20                   526
#define IDM_DXLITEM21                   527
#define IDM_DXLITEM22                   528
#define IDM_DXLITEM23                   529
#define IDM_DXLITEM24                   530
#define IDM_DXLITEM25                   531
#define IDM_DXLITEM26                   532
#define IDM_DXLITEM27                   533
#define IDM_DXLITEM28                   534
#define IDM_DXLITEM29                   535
#define IDM_TITLE                       536
#define IDM_EXEDIT                      537
#define IDM_BIGBUTTON                   538
#define IDM_INSERTDATE                  539
#define IDM_INSERTTIME                  540
#define IDM_ICONSEL                     541
#define IDM_ICONIMG00                   542
#define IDM_ICONIMG01                   543
#define IDM_ICONIMG02                   544
#define IDM_ICONIMG03                   545
#define IDM_ICONIMG04                   546
#define IDM_ICONIMG05                   547
#define IDM_ICONIMG06                   548
#define IDM_ICONIMG07                   549
#define IDM_ICONIMG08                   550
#define IDM_ICONIMG09                   551
#define IDM_ICONIMG10                   552
#define IDM_ICONIMG11                   553
#define IDM_ICONIMG12                   554
#define IDM_ICONIMG13                   555
#define IDM_PRINTCHIP                   556
#define IDM_COLORPRINT                  557
#define IDM_ARRANGE_TITLE               558
#define IDM_ARRANGE_ALL                 559
#define IDM_ABLEND_075                  561
#define IDM_ABLEND_050                  562
#define IDM_ABLEND_025                  563
#define IDM_ABLEND_000                  564
#define IDM_ABLEND_FREE                 565
#define IDM_UPDATEEXTICONS              567
#define IDM_SETDEFAULT                  569
#define IDD_LINK                        569
#define IDD_TIMER                       570
#define IDD_PASSWORD                    572
#define IDD_RESIZABLEMEMOEDIT           573
#define IDD_PRINTCHIPDLG                574
#define IDD_ALPHABLEND                  576
#define IDI_ICON1                       578
#define IDI_ICON2                       579
#define IDS_ABSENCE                     600
#define IDS_ALREADY_EXEC                601
#define IDS_CALCRESIZE                  602
#define IDS_CANCELBUTTON                603
#define IDS_CANCELED                    604
#define IDS_CAPTION_EDIT                605
#define IDS_CAPTION_NEW                 606
#define IDS_CAPTION_SEND                607
#define IDS_CELPOPUP                    608
#define IDS_CHECKDEL                    609
#define IDS_COLORBUTTON                 610
#define IDS_DELLOGTOOBIG                611
#define IDS_DELONQUITBUTTON             612
#define IDS_DISTRIBUTEEMPTY             613
#define IDS_DONOTVIEW                   614
#define IDS_DXLEDITHELPERBUTTON         615
#define IDS_DXLPOPUP                    616
#define IDS_DXLSELBUTTON                617
#define IDS_EXITINFO                    618
#define IDS_EXPORTFILTER                619
#define IDS_FONTBUTTON                  620
#define IDS_FONTCOLORBUTTON             621
#define IDS_FORCEDEND                   622
#define IDS_FORMATMISMATCH              623
#define IDS_FORTUNE                     624
#define IDS_FORTUNE_RESULT1             625
#define IDS_FORTUNE_RESULT2             626
#define IDS_FORTUNE_RESULT3             627
#define IDS_FORTUNE_RESULT4             628
#define IDS_FORTUNE_RESULT5             629
#define IDS_FORTUNE_RESULT6             630
#define IDS_ILLEGALTIME                 631
#define IDS_LINKBUTTON                  632
#define IDS_LINKFILEFILTER              633
#define IDS_LINKPARAMFILTER             634
#define IDS_MEMOCREATEDAY               635
#define IDS_MEMOEMPTY                   636
#define IDS_MEMORYINFO                  637
#define IDS_MEMOSTOCKDAY                638
#define IDS_MISSMATCHEXTENDED           639
#define IDS_MISSMATCHEXTENEDEDVERSION   640
#define IDS_NOSAVEDEL                   641
#define IDS_NOTFOUNDEXTENDEDDLL         642
#define IDS_NOTSUPPORTFORMAT            643
#define IDS_NOWCANCEL                   644
#define IDS_OKBUTTON                    645
#define IDS_OPENRESULT                  646
#define IDS_PACKMSG                     647
#define IDS_PWBUTTON                    648
#define IDS_PWLOCKDEL                   649
#define IDS_RECEIVELOGTOOBIG            650
#define IDS_RESEARCH_MSG1               651
#define IDS_RESEARCH_MSG2               652
#define IDS_RESEARCH_MSG3               653
#define IDS_RESOURCEINFO                654
#define IDS_SENDCANCELED                655
#define IDS_SENDEND                     656
#define IDS_SENDERROR                   657
#define IDS_SENDNOWCANCEL               658
#define IDS_SETREG_DLL                  659
#define IDS_SPESIALMENU                 660
#define IDS_STOCKLIST                   661
#define IDS_TEMPLETBUTTON               662
#define IDS_TEMPLETSUBMENU              663
#define IDS_TEMPLETSUBMENU_S            664
#define IDS_TEXTFILTER                  665
#define IDS_TIMEOUT                     666
#define IDS_TIMERBUTTON                 667
#define IDS_TRAYCHIP_HIDE               668
#define IDS_TRAYCHIP_NORMAL             669
#define IDS_TRAYCHIP_RECEIVE            670
#define IDS_UNDEFINECODE                671
#define IDS_USERCANCELED                672
#define IDS_VERHEADER                   673
#define IDS_VEROLDNOTIFY                674
#define IDS_VERSION                     675
#define IDS_VERSIONMISMATCH             676
#define IDS_WARNINGCREATEDATAFILE       677
#define IDS_WEEKDATA                    678
#define IDS_ZORDERBUTTON                679
#define IDS_NORMAL_ZORDER               680
#define IDS_TOP_ZORDER                  681
#define IDS_BOTTOM_ZORDER               682
#define IDS_TITLEBUTTON                 683
#define IDS_INSERTDATEBUTTON            684
#define IDS_INSERTTIMEBUTTON            685
#define IDS_ICONSELBUTTON               686
#define IDS_TEMPLETMSG                  687
#define IDS_OTHERCHIP                   688
#define IDS_CHIPCATALOG                 689
#define IDS_ALPHABLEND                  690
#define IDS_ALPHABLENDCAPTION           691
#define IDS_UPDATEICONS                 692
#define IDS_RENOTIFY                    693
#define IDS_FAILEDLOAD                  694
#define IDS_REG_AFTERBACKCOLOR          800
#define IDS_REG_AFTERFORECOLOR          801
#define IDS_REG_APPENDPOS               802
#define IDS_REG_APPENDSIGNATURE         803
#define IDS_REG_APPENDTIME              804
#define IDS_REG_ARRANGEICONDLL          805
#define IDS_REG_ARRANGENORMALDLL        806
#define IDS_REG_AUTOIMEOPEN             807
#define IDS_REG_AUTORESIZE              808
#define IDS_REG_AUTOTRIMING             809
#define IDS_REG_BACKCOLOR               810
#define IDS_REG_BEFOREBACKCOLOR         811
#define IDS_REG_BEFOREFORECOLOR         812
#define IDS_REG_CELMENU                 813
#define IDS_REG_CELMENUSEPARATOR        814
#define IDS_REG_CELPATH                 815
#define IDS_REG_CHECKDELONQUIT          816
#define IDS_REG_COMPATIBLEOU            817
#define IDS_REG_DATAFILE                818
#define IDS_REG_DATALISTFILTER          819
#define IDS_REG_DATALISTREVERSE         820
#define IDS_REG_DEFAULTNXL              821
#define IDS_REG_DELLISTFILTER           822
#define IDS_REG_DELLISTREVERSE          823
#define IDS_REG_DXLMENU                 824
#define IDS_REG_DXLPATH                 825
#define IDS_REG_ENABLENODELIST          826
#define IDS_REG_ENABLENXLGROUP          827
#define IDS_REG_ENABLESPMENU            828
#define IDS_REG_ENABLETEMPLET           829
#define IDS_REG_EXPORTFOLDER            830
#define IDS_REG_FILEPATH                831
#define IDS_REG_FLATMENU                832
#define IDS_REG_FORECOLOR               833
#define IDS_REG_FULLLOGGINGRECEIVECHIP  834
#define IDS_REG_FULLLOGGINGSENDCHIP     835
#define IDS_REG_GENERATIONCOUNT         836
#define IDS_REG_GLOBALPASSWORD          837
#define IDS_REG_HIDEBACK                838
#define IDS_REG_HIDERECEIVE             839
#define IDS_REG_HIDESTART               840
#define IDS_REG_HOTKEY                  841
#define IDS_REG_ICONINDEX               842
#define IDS_REG_LDBLCLKFUNC             843
#define IDS_REG_LOGFONT                 844
#define IDS_REG_LOGGINGDELCHIP          845
#define IDS_REG_LOGGINGRECEIVECHIP      846
#define IDS_REG_LOGGINGSENDCHIP         847
#define IDS_REG_MDBLCLKFUNC             848
#define IDS_REG_NETWORKENABLE           849
#define IDS_REG_NOCHECKDELETE           850
#define IDS_REG_NODELISTPATH            851
#define IDS_REG_NOTIFIYVERSION          852
#define IDS_REG_NOTIFYRECEIVE           853
#define IDS_REG_NXLMENU                 854
#define IDS_REG_NXLPATH                 855
#define IDS_REG_OPENCHECK               856
#define IDS_REG_PACKSEND                857
#define IDS_REG_POPUPRECEIVE            858
#define IDS_REG_RECEPTIONDXL            859
#define IDS_REG_RECEPTIONLINK           860
#define IDS_REG_RECEPTIONTIMER          861
#define IDS_REG_RESUMEDELAY             862
#define IDS_REG_SIGNATURE               863
#define IDS_REG_TEMPLETFILE             864
#define IDS_REG_USERCOLORS              865
#define IDS_REG_WAREHOUSEPATH           866
#define IDS_REG_EXEDIT                  867
#define IDS_REG_BIGBUTTON               868
#define IDS_REG_EXEDITRECT              869
#define IDS_REG_AUTOSCROLL              870
#define IDS_REG_INITALDERAY             871
#define IDS_REG_SENDDLGAUTOCLOSE        872
#define IDS_REG_COLORPRINT              873
#define IDS_REG_ARRANGETITLEDLL         874
#define IDS_REG_ARRANGEALLDLL           875
#define IDS_REG_CATALOG                 876
#define IDS_REG_RECEIVEANDSAVE          877
#define IDS_REG_MODIFYANDSAVE           878
#define IDS_REG_EXPANDSENDTREE          879
#define IDS_REG_DELETEAFTERSEND         880
#define IDS_REG_DEFAULT                 881
#define IDS_REG_MULTIUSER               882
#define IDS_REG_DEFAULTDXLID            883
#define IDS_REG_DELONQUIT2RCV           884

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        580
#define _APS_NEXT_COMMAND_VALUE         570
#define _APS_NEXT_CONTROL_VALUE         313
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
