//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SetReg.rc
//
#define IDB_ICONIMG                     100
#define IDD_CHIPEXDLL                   101
#define IDD_CUSTOMEXT                   102
#define IDD_CUSTOMNETWORK               103
#define IDD_DESIGN                      104
#define IDD_DRAWEXDLL                   105
#define IDD_EXTDLL                      106
#define IDD_INTERFACE                   107
#define IDD_NETWORKEXT                  108
#define IDD_NETWORKPAGE                 109
#define IDD_SECURITY                    110
#define IDD_TEMPLET                     111
#define IDS_EXSAMPLE                    150
#define IDS_INVALID                     151
#define IDS_MISMATCHOLDPW               152
#define IDS_MISSMATCHEXTENDED           153
#define IDS_MISSMATCHEXTENEDEDVERSION   154
#define IDS_NOTEQUPW                    155
#define IDS_NOTFOUNDEXTENDEDDLL         156
#define IDS_PROPSHT_CAPTION             157
#define IDS_VERYSHORTPW                 158
#define IDS_REG_AFTERBACKCOLOR          200
#define IDS_REG_AFTERFORECOLOR          201
#define IDS_REG_APPENDPOS               202
#define IDS_REG_APPENDSIGNATURE         203
#define IDS_REG_APPENDTIME              204
#define IDS_REG_ARRANGEICONDLL          205
#define IDS_REG_ARRANGENORMALDLL        206
#define IDS_REG_AUTOIMEOPEN             207
#define IDS_REG_AUTORESIZE              208
#define IDS_REG_AUTOTRIMING             209
#define IDS_REG_BACKCOLOR               210
#define IDS_REG_BEFOREBACKCOLOR         211
#define IDS_REG_BEFOREFORECOLOR         212
#define IDS_REG_CELMENU                 213
#define IDS_REG_CELMENUSEPARATOR        214
#define IDS_REG_CELPATH                 215
#define IDS_REG_CHECKDELONQUIT          216
#define IDS_REG_COMPATIBLEOU            217
#define IDS_REG_DATALISTFILTER          218
#define IDS_REG_DATALISTREVERSE         219
#define IDS_REG_DEFAULTNXL              220
#define IDS_REG_DELLISTFILTER           221
#define IDS_REG_DELLISTREVERSE          222
#define IDS_REG_DXLMENU                 223
#define IDS_REG_DXLPATH                 224
#define IDS_REG_ENABLETEMPLET           225
#define IDS_REG_FILEPATH                226
#define IDS_REG_FLATMENU                227
#define IDS_REG_FORECOLOR               228
#define IDS_REG_FULLLOGGINGRECEIVECHIP  229
#define IDS_REG_FULLLOGGINGSENDCHIP     230
#define IDS_REG_GLOBALPASSWORD          231
#define IDS_REG_HIDEBACK                232
#define IDS_REG_HIDERECEIVE             233
#define IDS_REG_HIDESTART               234
#define IDS_REG_HOTKEY                  235
#define IDS_REG_ICONINDEX               236
#define IDS_REG_LDBLCLKFUNC             237
#define IDS_REG_LOGFONT                 238
#define IDS_REG_LOGGINGDELCHIP          239
#define IDS_REG_LOGGINGRECEIVECHIP      240
#define IDS_REG_LOGGINGSENDCHIP         241
#define IDS_REG_MDBLCLKFUNC             242
#define IDS_REG_NETWORKENABLE           243
#define IDS_REG_NOCHECKDELETE           244
#define IDS_REG_NOTIFIYVERSION          245
#define IDS_REG_NOTIFYRECEIVE           246
#define IDS_REG_NXLMENU                 247
#define IDS_REG_NXLPATH                 248
#define IDS_REG_OPENCHECK               249
#define IDS_REG_PACKSEND                250
#define IDS_REG_POPUPRECEIVE            251
#define IDS_REG_RECEPTIONDXL            252
#define IDS_REG_RECEPTIONLINK           253
#define IDS_REG_RECEPTIONTIMER          254
#define IDS_REG_RESUMEDELAY             255
#define IDS_REG_SIGNATURE               256
#define IDS_REG_TEMPLETFILE             257
#define IDS_REG_USERCOLORS              258
#define IDS_REG_WAREHOUSEPATH           259
#define IDS_REG_GENERATIONCOUNT         260
#define IDS_REG_ARRANGETITLEDLL         261
#define IDS_REG_ARRANGEALLDLL           262
#define IDS_REG_RECEIVEANDSAVE          263
#define IDS_REG_MODIFYANDSAVE           264
#define IDS_REG_DELETEAFTERSEND         265
#define IDS_REG_DEFAULT                 266
#define IDS_REG_MULTIUSER               267
#define IDS_REG_DELONQUIT2RCV           268
#define IDS_REG_DEFAULTDXLID            269
#define IDC_ALLPASSWORD                 400
#define IDC_ARRANGEDLL_ABOUT            401
#define IDC_ARRANGEDLL_CONFIG           402
#define IDC_ARRANGEDLL_PATH             403
#define IDC_ARRANGEDLL_SEL              404
#define IDC_ARRANGEDLL                  405
#define IDC_AUTOTRIMMING                409
#define IDC_CALCDEFAULT                 410
#define IDC_CALCNOMOVE                  411
#define IDC_CEXEC                       412
#define IDC_CHECKPASSWORD               413
#define IDC_CHIPEXDLLABOUT              414
#define IDC_CHIPEXDLLCONFIG             415
#define IDC_CHIPEXDLLDELETE             416
#define IDC_CHIPEXDLLEDIT               417
#define IDC_CHIPEXDLLLIST               418
#define IDC_CHIPEXDLLMENUTEXT           419
#define IDC_CHIPEXDLLNAME               420
#define IDC_CHIPEXDLLSEL                421
#define IDC_CHIPEXSETSEPA               422
#define IDC_COLOR                       423
#define IDC_COMPATIBLEOU                424
#define IDC_CREEDIT                     425
#define IDC_CSEND                       426
#define IDC_CSMALLBIG                   427
#define IDC_CTITLE                      428
#define IDC_DATAFILE                    429
#define IDC_DATAFILESEL                 430
#define IDC_DELAYSPIN                   431
#define IDC_DELLOG                      432
#define IDC_DELONQUITDEFAULT            433
#define IDC_DESIGNTYPE                  434
#define IDC_DELONQUIT2RCV               434
#define IDC_DOWNITEM                    435
#define IDC_DRAWEXDELETE                436
#define IDC_DRAWEXDLLABOUT              437
#define IDC_DRAWEXDLLCONFIG             438
#define IDC_DRAWEXDLLMENUTEXT           439
#define IDC_DRAWEXDLLNAME               440
#define IDC_DRAWEXDLLSEL                441
#define IDC_DRAWEXEDIT                  442
#define IDC_DRAWEXLIST                  443
#define IDC_DROPINWITHUTL               444
#define IDC_DXLOK                       445
#define IDC_ENABLENETWORK               446
#define IDC_ENABLETEMPLET               447
#define IDC_FIRSTONCEHIDE               448
#define IDC_FONT                        449
#define IDC_HIDEBACK                    450
#define IDC_HIDESTART                   451
#define IDC_HODEBACK                    452
#define IDC_HOTKEYLIST                  453
#define IDC_ICONLIST                    454
#define IDC_IMEAUTO                     455
#define IDC_INFOHIDE                    456
#define IDC_LEXEC                       457
#define IDC_LREEDIT                     458
#define IDC_LSEND                       459
#define IDC_LSMALLBIG                   460
#define IDC_LTITLE                      461
#define IDC_MENUFLAT                    462
#define IDC_NEWPASSWORD                 463
#define IDC_NOCHECKDELETE               464
#define IDC_NXLABOUT                    465
#define IDC_NXLCONFIG                   466
#define IDC_NXLINSTALL                  467
#define IDC_NXLLIST                     468
#define IDC_NXLUNINSTALL                469
#define IDC_OLDPASSWORD                 470
#define IDC_READYDELAY                  471
#define IDC_RECEIVECHIPHIDE             472
#define IDC_RECEIVELOG                  473
#define IDC_RECEIVELOGFULL              474
#define IDC_RECEPTIONDXL                475
#define IDC_RECEPTIONLINK               476
#define IDC_RECEPTIONTIMER              477
#define IDC_SAMPLE                      478
#define IDC_SENDLOG                     479
#define IDC_SENDLOGFULL                 480
#define IDC_SENDOPENDEFAULT             481
#define IDC_SENDPACKDEFAULT             482
#define IDC_SHELLEXECOK                 483
#define IDC_SIGNATURE                   484
#define IDC_TEMPLETDEL                  485
#define IDC_TEMPLETLIST                 486
#define IDC_TIMEROK                     487
#define IDC_UPITEM                      488
#define IDC_VERUNNOTIFY                 489
#define IDC_GENERATIONCOUNT             490
#define IDC_GENERATIONCOUNTSPIN         491
#define IDC_MFSAVE                      492
#define IDC_RCSAVE                      493
#define IDC_ICONSEL                     494
#define IDC_DELETEAFTERSEND             495
#define IDM_ICONIMG00                   542
#define IDM_ICONIMG01                   543
#define IDM_ICONIMG02                   544
#define IDM_ICONIMG03                   545
#define IDM_ICONIMG04                   546
#define IDM_ICONIMG05                   547
#define IDM_ICONIMG06                   548
#define IDM_ICONIMG07                   549
#define IDM_ICONIMG08                   550
#define IDM_ICONIMG09                   551
#define IDM_ICONIMG10                   552
#define IDM_ICONIMG11                   553
#define IDM_ICONIMG12                   554
#define IDM_ICONIMG13                   555
#define IDR_DXLLISTMENU                 600
#define IDM_UPDRAWEX                    601
#define IDM_DOWNDRAWEX                  602
#define IDM_SETDEFAULTDXL               32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1003
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         494
#define _APS_NEXT_SYMED_VALUE           158
#endif
#endif
